version: '3.9'


services: 

  device:

    build: ./device

    ports:
      - 5005:5000

    command: 'python3 /app.py && tail -F anything'

  desktopserver1:

    build: ./desktopserver 

    ports:
      - 5001:5000

    command: 'python3 /app.py && tail -F anything'

    
  desktopserver2:

    build: ./desktopserver 

    ports:
      - 5002:5000

    command: 'python3 /app.py && tail -F anything'


  mobileserver1:

    build: ./mobileserver 

    ports:
      - 5003:5000

    command: 'python3 /app.py && tail -F anything'


  mobileserver2:

    build: ./mobileserver 

    ports:
      - 5004:5000

    command: 'python3 /app.py && tail -F anything'
